Added timeout option to authentication module
cyberark/ansible-security-automation-collection pull request #48
Opened 2022-11-04 20:57 UTC by mrendo

### Desired Outcome

We noticed now we have turned on two factor we have a problem with the module timing out before we have pressed the push notification.

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

Adding a timeout option to the authentication module, tested it using a local copy of the module with my Cyberark system

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]  #47

CyberArk internal issue link: [insert issue ID]()

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2023-01-10 16:04 UTC, infamousjoeg requested changes
After bumping version to 1.0.16 this looks good to me and can be merged.

2023-01-10 16:04 UTC, infamousjoeg commented on galaxy.yml
> +version: "1.0.15"
Please bump this to 1.0.16

2023-01-10 19:41 UTC, mrendo commented on galaxy.yml
> +version: "1.0.15"
All done I believe thanks @infamousjoeg

2023-01-11 02:12 UTC, infamousjoeg approved these changes

2023-01-11 02:13 UTC, infamousjoeg commented
Will merge and publish to Galaxy in the morning.

2023-01-11 13:24 UTC, merged